//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAA.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ApplicantProfile
    {
        public int Id { get; set; }

        [Required(ErrorMessage="Name is Required.")]
        [MinLength(3, ErrorMessage = "Name entered is too short.")]
        [MaxLength(50, ErrorMessage="Name entered is too long.")]
        public string ApplicantName { get; set; }

        [Required(ErrorMessage = "Address is Required.")]
        [MinLength(0, ErrorMessage = "Address entered is too short.")]
        [MaxLength(50, ErrorMessage = "Name entered is too long.")]
        public string ApplicantAddress { get; set; }

        [Required(ErrorMessage = "Phone number is Required.")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Value must be numeric.")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Email Address number is Required.")]
        [EmailAddress]
        public string Email { get; set; }
        public string UserId { get; set; }
    }
}
